# Generated by Django 5.2.3 on 2025-06-14 09:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_profile_visitorlog_delete_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitorlog',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
