# Generated by Django 5.2.3 on 2025-06-14 09:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_visitorlog_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitorlog',
            name='visited_at',
        ),
        migrations.AlterField(
            model_name='visitorlog',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
